website/index.html

Check out the preview deployment and let me know your thoughts

website changes

---

package.json
packages/prettier-plugin-ripple/package.json
packages/ripple/package.json
packages/vite-plugin-ripple/package.json
playground/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

chore: migrate to pnpm catalogs

---

templates/basic/package-lock.json
templates/basic/package.json

it was breaking on install otherwise.
also added node 20 as the minimum support.

update basic template deps

---

README.md
packages/ripple/src/runtime/array.js
packages/ripple/src/runtime/index.js
packages/ripple/tests/array.test.ripple
packages/ripple/tests/for.test.ripple
packages/ripple/tests/use.test.ripple
packages/ripple/types/index.d.ts

- also adds RippleArray.from and RippleArray.of static methods

replace array with RippleArray

---

packages/ripple/tests/context.test.ripple
playground/src/App.ripple

Just remove the argument in context.get

fix context get api example

---

packages/ripple/src/runtime/set.js

oops.
we should probably start jsdoc'ing code sometime soon.

fix: set missing scope on has

---

README.md

Change 
```jsx
<button onClick={() => $count++}>Increment</button>
```
to
```jsx
<button onClick={() => $count++}>{'Increment'}</button>
```

fix a readme code sample

---

.github/workflows/pkg.pr.new.yml

approval check is blocking the publish job, whoops.

chore(ci): remove PR filter for approval check

---

website/index.html
website/llms.txt
website/robots.txt
website/sitemap.xml

This should help AI bot crawlers better understand Ripple in the short term. Let me know if any of the examples or code look off as I had Claude Code write this for me :)

Add llms.txt

---

packages/ripple/src/runtime/array.js
packages/ripple/src/runtime/internal/client/index.js
packages/ripple/src/runtime/internal/client/runtime.js
packages/ripple/src/runtime/map.js
packages/ripple/src/runtime/set.js
packages/ripple/tests/map.test.ripple

also fixes `$length` setter on the array to not unnecessarily register deps

Safe scope

---

packages/ripple/src/runtime/array.js

Add `val, start, end, params` for fill function

feat: update fill function to accept parameters

---

website/playground.html

The playground is watched for code changes, which triggers generating a shareable URL (using URL hash).
Users can copy the URL from address bar and share it.
This is a preliminary implementation till the docs website is ready. We can then integrate the playground in it and add UI elements (e.g. share button).

playground: generate shareable URLs

---

packages/ripple/src/compiler/phases/3-transform/index.js
packages/ripple/src/runtime/internal/client/index.js
packages/ripple/src/runtime/internal/client/runtime.js
packages/ripple/tests/basic.test.ripple

fixes #175 
- introduces `call_property` for handling bracketed function calls
**Better viewed with hide whitespace**
- currently blocks #171

fixes bracketed function calls #175

---

packages/ripple/src/compiler/phases/3-transform/index.js
packages/ripple/tests/basic.test.ripple

Fixes empty literal bug (backticks).
For reference see issue: #213

fix: empty template literal bug

---

packages/create-ripple/package.json
packages/create-ripple/src/lib/project-creator.js
packages/create-ripple/src/lib/prompts.js
packages/create-ripple/tests/integration/project-creator.test.js
packages/create-ripple/tests/unit/prompts.test.js

Fixed tailwind wrong structure once invoked byt the create-app.

fix: create-app tailwind wrong structure

---

packages/ripple/src/compiler/phases/2-analyze/index.js
packages/ripple/src/compiler/phases/3-transform/index.js
packages/ripple/src/compiler/utils.js
packages/ripple/src/runtime/internal/client/render.js
packages/ripple/src/runtime/internal/client/utils.js
packages/ripple/src/utils/events.js
packages/ripple/tests/basic.test.ripple

fix: events in spread props

---

website/index.html

Fixing typo

---

.github/workflows/ci.yml
.github/workflows/pkg.pr.new.yml
packages/create-ripple/package.json
packages/create-ripple/tests/integration/cli.test.js
packages/create-ripple/tsdown.config.js
pnpm-lock.yaml

I haven't added a `build` command to the monorepo's package.json, mostly because it's only this package that requires a build step. lmk if I should.
before:
```
ripple/packages/create-ripple $ pnpx npm-size .
√ current directory 2.43 MB
```
after:
```
ripple/packages/create-ripple $ pnpx npm-size .
√ current directory 403.44 KB
```

bundle cli

---

packages/create-ripple/package.json

tell npm to include bundled create-ripple

---

README.md
website/docs/guide/styling.md
website/public/llms.txt

docs: Fix small issues with docs in the inline styles section

---

packages/ripple/src/compiler/phases/3-transform/client/index.js
packages/ripple/src/runtime/internal/client/html.js
packages/ripple/tests/client/html.test.ripple

- ignore white space changes when looking at the diff
implements #361

adds support for {html str} inside svg and mathml

---

website/.vitepress/components/LiveCodes.vue
website/.vitepress/theme/styles.css

This PR improves styles for action buttons above the playground to be more consistent with the website styles.

edit playground actions styles

---

website/.vitepress/components/LiveCodes.vue
website/.vitepress/theme/styles.css

This PR adds playground title.
The title also persists in the shared URL.
It can be used later on social media cards (using open graph tags generated on server-side) for shared URLs.

add playground title

---

website/.vitepress/components/LiveCodes.vue

I missed a console.log in the last PR. Sorry!

remove console.log

---

packages/ripple/src/runtime/create-subscriber.js
packages/ripple/src/runtime/index-client.js
packages/ripple/src/runtime/index-server.js
packages/ripple/src/runtime/internal/client/runtime.js
packages/ripple/src/runtime/media-query.js
packages/ripple/src/runtime/reactive-value.js
packages/ripple/src/runtime/url-search-params.js
packages/ripple/src/runtime/url.js
packages/ripple/tests/client/media-query.test.ripple
packages/ripple/tests/client/url-search-params.test.ripple
packages/ripple/tests/client/url.test.ripple
packages/ripple/types/index.d.ts

feat: add reactive URL, URLSearchParams, MediaQuery

---

README.md
website/docs/guide/components.md
website/public/llms.txt

Add portal docs

---

packages/ripple/src/runtime/internal/client/composite.js
packages/ripple/src/runtime/internal/client/render.js
packages/ripple/tests/client/dynamic-elements.test.ripple

Add support for dynamic elements.
Implements #266

Add dynamic elements

---

packages/ripple/src/compiler/phases/3-transform/server/index.js
packages/ripple/tests/client/switch.test.ripple
packages/ripple/tests/server/switch.test.ripple

@trueadm 
Introduced switch-case statement support in Ripple SSR
Also added tests for switch-case in both client and server side rendering.

Add support for switch-case statements in SSR

---

website/docs/examples.ts

This PR adds a playground example for Switch statements

add example for switch statement

---

README.md
packages/prettier-plugin-ripple/src/index.test.js
website/docs/guide/control-flow.md
website/public/llms.txt

Added the code examples demonstrating usage of `switch-case` in Ripple

Added docs for switch-case in RIpple

---

packages/prettier-plugin-ripple/src/index.test.js
packages/ripple/src/compiler/phases/3-transform/client/index.js
packages/ripple/src/compiler/phases/3-transform/server/index.js
packages/ripple/tests/client/__snapshots__/compiler.test.ripple.snap
packages/ripple/tests/client/compiler.test.ripple
packages/ripple/tests/server/__snapshots__/compiler.test.ripple.snap
packages/ripple/tests/server/compiler.test.ripple

fix: remove ts types from function parameters with default

---

packages/ripple/src/compiler/phases/3-transform/server/index.js
packages/ripple/tests/client/composite.test.ripple
packages/ripple/tests/server/composite.test.ripple

generics: enable all tests
