packages/ripple/src/compiler/phases/3-transform/index.js

ran into an issue when calling a child component from App, this fixes it.  It looks like optional chaining was already above this line with the usage of `metadata`

add optional chaining as metadata can be undefined

---

packages/ripple/src/runtime/internal/client/runtime.js

-    with reactive obj prop { $count : 1 }, obj.$count -- doesn't work. Instead it increase the count. 
-    decrement the value instead of always incrementing it.

Fixed reactive object property decrement not working issue

---

packages/ripple-vscode-plugin/syntaxes/ripple.tmLanguage.json

Replaced three variable-length lookbehinds with fixed-length lookaheads in ripple.tmLanguage.json to fix grammar loading errors.
this should hopefully fix this error when building grammar for linguist:
```shell
1 errors found in new grammar 'repository `vendor/grammars/ripple` (from https://github.com/trueadm/ripple.git)':
- Invalid regex in grammar: `source.ripple` (in `packages/ripple-vscode-plugin/syntaxes/ripple.tmLanguage.json`) contains a malformed regex (regex "`(?!(?<![_$[:alnum:]])(?:(?<=\.\.`...": lookbehind assertion is not fixed length (at offset 731))
```
Notes:
- Extension should work like before (tested)

fix grammar regex: remove variable-length lookbehind

---

templates/basic/package-lock.json

Looks like this package got caught in a find/replace all for 0.2.14 -> 0.2.15

revert tinyglobby to valid version

---

playground/src/App.ripple

This might just be a Linux issue (although it repros in both Chrome and Firefox), but the `<code>` in the playground is unreadable for me. Before and after:
Very exciting project BTW!

fix `<code>` legibility in the playground

---

website/playground.html

This is a follow up for #76 
It checks latest published version from https://data.jsdelivr.com/v1/packages/npm/ripple
and uses that in the playground to avoid the cache problem outlined in #76
In addition, the css unit `dvh` is used instead of `vh` to avoid hiding the lower part (including console & compiled code viewer) in mobile.

use latest ripple version in playground

---

.github/workflows/livecodes-post-comment.yml
.github/workflows/livecodes-preview.yml
.livecodes/playground.json

This PR adds github actions to preview PR changes in playground. See [Preview in LiveCodes](https://github.com/live-codes/preview-in-livecodes).
It uses pkg.pr.new to load Ripple compiler, runtime and formatter so that they can be tried in the playground before merge.
Example: https://github.com/hatemhosny/racing-bars/pull/211#issuecomment-3272401255
Please note: 
- The GH actions need to be merged to the main branch to work ([details](https://github.com/live-codes/preview-in-livecodes?tab=readme-ov-file#usage)).
- This needs the pkg.pr.new packages to be available.

Preview PRs in playground

---

README.md

Changes in Detail:
Corrected specifcally → specifically
Removed redundant words for clarity (e.g., “still … still work”).
Improved sentence flow (that combined → that combine).
industry leading →  industry-leading

fix: typos and improve readability in README.md

---

README.md

This pull request makes minor documentation improvements in the `README.md` file by correcting a couple of spelling errors.
- Documentation fixes:
* Corrected "expressitivity" to "expressivity" to improve clarity in the explanation of reactivity transport.
* Fixed a typo, changing "specifcally" to "specifically" in the description of composite component usage.

Fix typos in reactivity section of README

---

.github/workflows/vsix.yml

Fixes https://github.com/trueadm/ripple/actions/runs/17696573863/job/50296820627
ran git show on the monorepo package.json rather than the extension's, so use the relative path instead.
```
CURRENT_VERSION=$(jq -r .version package.json)
PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq -r .version) <------
Outputs: 
Current version:  0.0.10
Previous version: null
Version was changed: null -> 0.0.10
```

fix version comparison for extension auto-publish workflow

---

packages/create-ripple/src/lib/project-creator.js
templates/basic/.gitignore
templates/basic/ripple.d.ts

- Fixed scaffolding templates to run only `git init` (currently commented to not run auto `git add` and `git commit`).
- Added missing type declaration file ripple.d.ts for `*.ripple` files to fix TS error in templates:  
`Cannot find module './App.ripple' or its corresponding type declaration`.

fix: Fixed TS errors in templates and added .gitignore

---

packages/ripple/src/compiler/phases/1-parse/index.js
packages/ripple/src/utils/patterns.js

Fixes #103 
Problem: The css content was skipped when computing source locations, leading to wrong values starting at the closing `style` tag.
Solution: Adjust the curLine and lineStart manually to take new lines into account.
I'm open to adding some tests in compiler.test.ripple if this approach seems ok

fix source location for style tag

---

packages/ripple/src/compiler/phases/1-parse/index.js
packages/ripple/tests/compiler.test.ripple

Should fix #173 
css content extraction was still not properly handled when starting with an id selector. The # was not included in the parser's identifier value.
Did not fix the failing tests in create-ripple since they are unrelated to this change. Seems like a windows/unix path issue

fix parser's css content extraction

---

README.md
packages/prettier-plugin-ripple/src/index.js
packages/prettier-plugin-ripple/src/index.test.js
packages/ripple-vscode-plugin/syntaxes/ripple.tmLanguage.json
packages/ripple/src/compiler/phases/1-parse/index.js
packages/ripple/src/compiler/phases/3-transform/index.js
packages/ripple/src/compiler/phases/3-transform/segments.js
packages/ripple/src/runtime/index.js
packages/ripple/src/runtime/internal/client/blocks.js
packages/ripple/src/runtime/internal/client/constants.js
packages/ripple/src/runtime/internal/client/index.js
packages/ripple/src/runtime/internal/client/render.js
packages/ripple/src/runtime/internal/client/runtime.js
packages/ripple/tests/ref.test.ripple
packages/ripple/types/index.d.ts
website/llms.txt

The `{@use}` decorator feature has always felt cumbersome, as people associate capturing the DOM element using a `ref`. Plus the `@` isn't something we've promoted before, so it doesn't make sense to use it here either. We can simplify this this feature to be `{ref fn}` or `{ref () => {…} }` or `{ref fn(a, b}`.

change decorator api to refs

---

packages/ripple/src/compiler/phases/2-analyze/prune.js
packages/ripple/tests/basic.test.ripple

Fixes #194 
This PR fixes a bug where the compiler did not correctly handle attributes starting with a dollar sign, such as `$class`.
`attribute_matches` function has been updated to correctly recognize attributes prefixed with a dollar sign.

fix: apply styles based on reactive attributes

---

packages/prettier-plugin-ripple/src/index.js
packages/prettier-plugin-ripple/src/index.test.js

- Added `@` to tracked `Identifier` nodes
- Added a test with multiple tracked value usages
- All existing tests passed
None 
- Issue #271

fix: keep @ when formatting (prettier)

---

packages/prettier-plugin-ripple/src/index.js
packages/prettier-plugin-ripple/src/index.test.js

closes #280
i have never worked on a prettier plugin before, so im not sure this is the right way to handle it, but i tested it and it worked :)

fix: type annotation formatting to property and object patterns

---

packages/create-ripple/package.json
packages/create-ripple/src/commands/create.js

Add missing graceful exist once project is successfully created.

Fix missing graceful exit on successful project creation

---

README.md
website/docs/guide/reactivity.md
website/public/llms.txt

Hello 👋 
Small typo fix 😃 `trackSlit` -> `trackSplit` in Readme

docs: fix typo

---

packages/ripple/package.json
packages/ripple/src/compiler/phases/3-transform/client/index.js
packages/ripple/src/runtime/internal/client/render.js
packages/ripple/src/runtime/internal/server/index.js
packages/ripple/tests/client/basic.test.ripple
pnpm-lock.yaml

Closes #322.
This PR adds the ability to specify arrays and objects in the class attribute via the tiny clsx library as suggested in the mentioned issue. For example:
```jsx
<div class={[
'hello',
'world',
isActive && 'active',
['nested', 'array'],
{
foo: isFoo,
bar: isBar,
},
]}>
{`This is an example`}
</div>
```
I added two new tests for the new functionality. Then I ran all tests:
```bash
pnpm test
```
All tests, including the two new ones I added, passed successfully. As far a I understand, no breaking changes here, `<div class="hello world" />` works like before.

feat: Implement support for arrays and objects in class attribute via clsx

---

packages/create-ripple/package.json
packages/create-ripple/vitest.config.js

Added silent mode for passing tests in the create-ripple package.
Also bumped version.

fix: output bloated when on passed tests in create-ripple

---

packages/ripple/src/utils/normalize_css_property_name.js

This is a followup PR to #362. It removes using `.has()`, using `.get()` directly instead. According to tests I've done, it yields 10 to 15% performance improvement in both Chrome and Firefox. Behavior stays the same, the tests still pass after this change.
Thanks to @leonidaz for the [comment](https://github.com/trueadm/ripple/pull/362#discussion_r2387509480)

perf: Speedup CSS property normalization by not using .has()

---

packages/ripple/tests/client/basic.test.ripple

A recent commit disallowed mutating tracked values inside computed `track()`. This test tries to mutate a tracked value inside a computed `track()`, and verifies that the error gets thrown.
Side note: is there a better way to catch errors and get their text in the test? This is the only solution I came up with that seemed to work.

test: Add test for mutating tracked value inside computed track() evaluation

---

packages/ripple-vscode-plugin/package.json

Hi, 
I saw while playing around with ripple that no logo is shown for .ripple files. So I thought of adding this for both light and dark mode. 
Maybe we can later decided separate icons for both modes. 
I'm not sure whether I should package the extension again or not and update that too with in this PR. 
It will be a huge help if someone can guide a little on what else I should do to get this PR merged.
P.S: This is my first PR to any library :)

Added ripple icon entry in contributes schema for both light & dark mode

---

packages/prettier-plugin-ripple/src/index.js
packages/prettier-plugin-ripple/src/index.test.js

Added TypeScript node support in prettier-plugin-ripple:
- TSTupleType
- TSIndexSignature
- TSConstructorType
- TSConditionalType
- TSMappedType
- TSQualifiedName
- TSIndexedAccessType
Solves #382 (hopefully everything is included now).

fix: prettier plugin missing types

---

packages/ripple-language-server/LICENSE
packages/ripple-language-server/README.md
packages/ripple-language-server/bin/ripple-language-server.js
packages/ripple-language-server/index.js
packages/ripple-language-server/package.json
packages/ripple-language-server/src/diagnosticPlugin.js
packages/ripple-language-server/src/server.js
packages/ripple-vscode-plugin/package.json
packages/ripple-vscode-plugin/src/server.js
packages/ripple/src/compiler/phases/3-transform/segments.js
packages/typescript-plugin-ripple/src/language.js
pnpm-lock.yaml

Closes #409
This PR extracts the LSP from the VS Code extension into its own package. The idea is to use the LSP in other editors. I successfully tested it in WebStorm, Sublime Text, and Neovim. Before I change the PR from draft, I have a few questions I'd like to ask people who understand the codebase better. Probably @trueadm and @leonidaz.
1) This:
```js
const initResult = server.initialize(
params,
createSimpleProject([getRippleLanguagePlugin()]),
[createRippleDiagnosticPlugin()],
);
```
seems to work in VS Code, but not in any other editor. All other editors correctly display compilation errors, but no TypeScript suggestions. I replaced `createSimpleProject` with `createTypeScriptProject`:
```js
const ts = require('typescript');
const initResult = server.initialize(
params, …
```

Extract LSP from VS Code extension
